### ISSUE TITLE
Add support for image links

### ISSUE THREAD

**Issue by garfieldbanks** [mindmup/mindmup#86]
If I have many images in my map, it can take a long time to save. I think it might be better if instead of putting all my images in the map file, I just had links. So I could just upload my image to imgur or something and then in the map file it would just have: `<img src="http://i.imgur.com/XYHiso4.jpg">`

**Comment by gojko** [comment]
mindmup 2.0 for google drive uses links from google photos. you can use that now from https://drive.mindmup.com.  adding image links from any URL isn't practical because of browser security requirements (the image servers need to support CORS, which is rarely the case). that's a browser limitation and we can't do anything about it.
